from socket import *
serverName = "10.20.203.167"
serverPort = 2020
clientSocket = socket(AF_INET, SOCK_STREAM)
clientSocket.connect((serverName,serverPort))
print("Welcome to the EXAM\n\n")

print("Question 1 :\n")
print("Who is the author of the book 'Nineteen Eighty Four'?")
print("A. Thomas Hardy\nB. Emile Zola\nC. George Orwell\nD. Walter Scott")
answer1 = input("Enter Answer\n")
clientSocket.send(answer1.encode())
check1 = clientSocket.recv(1024)
print("From Server: ", check1.decode())

print("Question 2 :\n")
print("Who wrote 'War and Peace'?")
print("A. Leo Tolstoy\nB. Mahatma Gandhi\nC. Charles Dickens\nD. Kipling")
answer2 = input("Enter Answer\n")
clientSocket.send(answer2.encode())
check2 = clientSocket.recv(1024)
print("From Server: ", check2.decode())

print("Question 3 :\n")
print("What is the name of the biggest planet in our solar system?")
print("A. Jupiter\nB. Saturn\nC. Sun\nD. Earth")
answer3 = input("Enter Answer\n")
clientSocket.send(answer3.encode())
check3 = clientSocket.recv(1024)
print("From Server: ", check3.decode())

print("Question 4 :\n")
print("Who invented the Car?")
print("A. Charles Babbage\nB. Elon Musk\nC. Johannes Gutenberg\nD. Carl Benz")
answer4 = input("Enter Answer\n")
clientSocket.send(answer4.encode())
check4 = clientSocket.recv(1024)
print("From Server: ", check4.decode())

print("Question 5 :\n")
print("This yellow cartoon character lives in a pineapple under the sea.")
print("A. Simpsons\nB. Spongebob\nC. Bert\nD. Tweety")
answer5 = input("Enter Answer\n")
clientSocket.send(answer5.encode())
check5 = clientSocket.recv(1024)
print("From Server: ", check5.decode())

print("Question 6 :\n")
print("On Wednesdays we wear __.")
print("A. Red\nB. Black\nC. Pink\nD. Purple")
answer5 = input("Enter Answer\n")
clientSocket.send(answer5.encode())
check5 = clientSocket.recv(1024)
print("From Server: ", check5.decode())

clientSocket.close()
